import { type WalletClient, type Abi, type Address, type Hash } from 'viem';
import workstreamAbi from '../generated/workstream.abi.json' with { type: 'json' };

export type CreateAndFundInput = { wallet: WalletClient; usdc: Address; contributor: Address; agent: Address; repo: string; milestone: string; budgetUnits: bigint; durationSeconds: bigint };

/**
 * Safe integration shape. The caller must provide the generated bytecode and
 * explicit constructor arguments from the current artifact. Every step waits
 * for a successful receipt before the next write.
 */
export async function createAndFund(input: CreateAndFundInput): Promise<Hash> {
  const abi = workstreamAbi as Abi;
  const [account] = await input.wallet.getAddresses();
  if (!account) throw new Error('Wallet has no account');
  throw new Error('Non-executing example: wire deploy bytecode and constructor from the pinned artifact after review.');
}
